### ISSUE TITLE
Distinguish performance improvements in some way

### ISSUE THREAD

**Issue by KristofferC** [JuliaCI/BenchmarkTrackers.jl#6]
It is also interesting to see performance improvements. It might be worth making these stick out somehow. Putting it in bold like the regressions would be confusing but maybe underlining or cursive?

**Comment by jrevels** [comment]
We could do italics instead of bold.

**Comment by tkelman** [comment]
Colors?

**Comment by jrevels** [comment]
I don't think GFM supports colors. That would be cool, though.

**Comment by KristofferC** [comment]
Github markdown does not support colors, right?

**Comment by KristofferC** [comment]
Could embed a small SVG with color or something maybe

**Comment by tkelman** [comment]
that sounds like more work than it's worth. emoji's for highlighting maybe?

**Comment by KristofferC** [comment]
Yeah, just thought about emoji's too. 

:white_check_mark:

:red_circle:

:heavy_exclamation_mark:

:small_red_triangle:

**Comment by tkelman** [comment]
:warning:
:chart_with_downwards_trend: 
:chart: 
:small_orange_diamond: 
:x:

**Comment by KristofferC** [comment]
Maybe there could be a setting in the markdown printer to chose between emojis and standard markdown stuff like bold and italics if someone wants to use the package without the Github infrastructure.

**Comment by jrevels** [comment]
Emojis are a great idea. I like :white_check_mark: for improvements and :x: for potential regressions.

> Maybe there could be a setting in the markdown printer to chose between emojis and standard markdown stuff like bold and italics if someone wants to use the package without the Github infrastructure.

Makes sense, but probably not something we need to be concerned about until somebody requests it.

**Comment by KristofferC** [comment]
Agreed.

**Comment by KristofferC** [comment]
Cool!
