### ISSUE TITLE
Possibility of a bit more structured output in the markdown reports

### ISSUE THREAD

**Issue by KristofferC** [JuliaCI/BenchmarkTrackers.jl#8]
With increasing number of benchmarks in BaseBenchmarks.jl I believe the generated markdown reports will get a bit cluttered.

I propose that when creating a set of benchmarks with the `@benchmarks` macro, a (unique?) string is also given which serves as an identifier for a collection of benchmarks.

The syntax could be
```
@benchmarks "collection_name" begin
        [(:sumelt, string(typeof(A)), size(A)) => perf_sumelt(A) for A in arrays]
        [(:sumeach, string(typeof(A)), size(A)) => perf_sumeach(A) for A in arrays]
        .
        .
end
```

The generated markdown report could then include a "table of contents" with reference links to each collection together with a status mark :x: or :white_check_mark: if any of the benchmarks in the collection had a performance increase / decrease.

I made an example of how such a generated markdown report could look here:

https://gist.github.com/KristofferC/b6e6066a89138bbe9581

I am going on vacation for two weeks tomorrow, else I could have started working on it myself. Just putting it here if anyone feels like working on it and get some feedback.

Any opinions? @jrevels @tkelman

**Comment by KristofferC** [comment]
By the way, https://chrome.google.com/webstore/detail/wide-github/kaalofacklcidaampbokdplbklpeldpj?hl=en makes it much easier to read the generated benchmarks tables.

**Comment by jrevels** [comment]
Looks like a good idea, I'll have to mull over the right way to implement it.

Also, thanks so much for that extension link, I just enabled it.

**Comment by jrevels** [comment]
> With increasing number of benchmarks in BaseBenchmarks.jl I believe the generated markdown reports will get a bit cluttered.

One other (easier) way to alleviate this would be to only put the significant results (the ones marked :x: or :white_check_mark:) in the markdown report. The other results could still be included in the JSON data, in case somebody wants to check absolute timings.

**Comment by jrevels** [comment]
The syntax you proposed gave me this idea. We could take this:

```julia
@benchmarks "prefix" begin
    ("bench1",...) => ...
    ("bench2",...) => ...
    ⋮
end
```

And have it mean this:

```julia
@benchmarks begin
    ("prefix", "bench1",...) => ...
    ("prefix", "bench2",...) => ...
    ⋮
end
```

Along with #9, this should basically give the result we want in the report (sorted sections) without having implement new semantics.

Doesn't solve the reference linking problem, though. It might be best to implement an `@url` macro for that:

```julia
@track tracker begin 
    @benchmarks "prefix" begin
        ("bench1",...) => ...
        ("bench2",...) => ...
        ⋮
    end
    @url "https://github.com/me/myrepo/contents.jl"
end
```

**Comment by KristofferC** [comment]
I am not sure what you mean with the "linking problem". Do you want to generate a link to the source file of the benchmark? What I meant was just a link to the header in the markdown report (as in my example link).

**Comment by jrevels** [comment]
> Do you want to generate a link to the source file of the benchmark?

Yeah, that's what I thought you meant, my bad. Linking back to the benchmark source is is a feature I originally wanted, but considered low priority, so I never got around to it.

**Comment by KristofferC** [comment]
This is fixed now imo.
